### ISSUE TITLE
proper CMakeLists.txt

### ISSUE THREAD

**Issue by SteffenSeckler** [HSU-HPC/MaMiCo#1]
@Thinkpiet or @wittmern do you have a proper CMakeLists.txt that is not käs(e and which actually works?

**Comment by Thinkpiet** [comment]
Hi @SteffenSeckler, thanks for the question! And sorry that this repo is such a mess and there is basically no documentation so far... 

The stuff that is in the master right now is not meant to be built with cmake, instead there are simple shell scripts e.g. [coupling/python-binding/make.sh](https://github.com/HSU-HPC/MaMiCo/blob/master/coupling/python-binding/make.sh) and [coupling/tests/build_couette/buildtest.sh](https://github.com/HSU-HPC/MaMiCo/blob/master/coupling/tests/build_couette/buildtest.sh). These should actually work (if you configure your
personal_settings file correctly).

If you really want to use CMake, there should be working CMakeLists.txt files in the projektleofelix branch, e.g. [CMakeLists.txt](https://github.com/HSU-HPC/MaMiCo/blob/projektleofelix/CMakeLists.txt)

**Comment by SteffenSeckler** [comment]
do you plan to change the build system at some point?
the cmake files currently look somewhat hacky

**Comment by Thinkpiet** [comment]
We have a proper CMake build system now, so I close this issue.
