### ISSUE TITLE
IndexingServiceTest does not compile and a test fails in sequential

### ISSUE THREAD

**Issue by LouieVoit** [HSU-HPC/MaMiCo#33]
In sequential mode:
1. IndexingServiceTest::testEdgeCases is calling IndexingService::getUniqueRankForMacroscopicCell but this method does not exist
2. No exceptions are thrown in IndexingServiceTest::testEdgeCases

**Comment by Thinkpiet** [comment]
I think this is an issue in your version of moretests branch that is already fixed in current master. See 647a9c5c8a9c7ad4c6e49738d46610eb7efd6e9e
